### ISSUE TITLE
hsp not starting

### ISSUE THREAD

**Issue by aycgit** [andune/HomeSpawnPlus#103]
hsp isnt starting for me i get this error:

01.07 04:56:47 [Server] INFO [HomeSpawnPlus] HomeSpawnPlus version 2.0-b610 is disabled
01.07 04:56:47 [Server] INFO [HomeSpawnPlus] Disabling HomeSpawnPlus v2.0-b610
01.07 04:56:47 [Server] INFO at java.lang.Thread.run(Thread.java:745) [?:1.8.0_65]
01.07 04:56:47 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:524) [spigot188.jar:git-Spigot-fdc1440-53fac9f]
01.07 04:56:47 [Server] INFO at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:263) [spigot188.jar:git-Spigot-fdc1440-53fac9f]
01.07 04:56:47 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.a(MinecraftServer.java:333) [spigot188.jar:git-Spigot-fdc1440-53fac9f]
01.07 04:56:47 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.k(MinecraftServer.java:378) [spigot188.jar:git-Spigot-fdc1440-53fac9f]
01.07 04:56:47 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.s(MinecraftServer.java:414) [spigot188.jar:git-Spigot-fdc1440-53fac9f]
01.07 04:56:47 [Server] INFO at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:317) [spigot188.jar:git-Spigot-fdc1440-53fac9f]
01.07 04:56:47 [Server] INFO at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:357) [spigot188.jar:git-Spigot-fdc1440-53fac9f]
01.07 04:56:47 [Server] INFO at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [spigot188.jar:git-Spigot-fdc1440-53fac9f]
01.07 04:56:47 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:340) [spigot188.jar:git-Spigot-fdc1440-53fac9f]
01.07 04:56:47 [Server] INFO at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321) [spigot188.jar:git-Spigot-fdc1440-53fac9f]
01.07 04:56:47 [Server] INFO at com.andune.minecraft.hsp.HomeSpawnPlusBukkit.onEnable(HomeSpawnPlusBukkit.java:77) [HomeSpawnPlus.jar:2.0]
01.07 04:56:47 [Server] INFO at com.andune.minecraft.hsp.HomeSpawnPlus.onEnable(HomeSpawnPlus.java:88) ~[HomeSpawnPlus.jar:2.0]
01.07 04:56:47 [Server] INFO at com.andune.minecraft.hsp.util.NameChangeUtil.cleanupDupUUIDs(NameChangeUtil.java:146) ~[HomeSpawnPlus.jar:2.0]
01.07 04:56:47 [Server] INFO at com.andune.minecraft.hsp.storage.yaml.PlayerDAOYaml.purgePlayer(PlayerDAOYaml.java:112) ~[HomeSpawnPlus.jar:2.0]
01.07 04:56:47 [Server] INFO com.andune.minecraft.hsp.shade.commonlib.FeatureNotImplemented
01.07 04:56:47 [Server] ERROR [HomeSpawnPlus] Caught exception loading plugin, shutting down
01.07 04:56:47 [Server] INFO [HomeSpawnPlus] Vault interface found and will be used for economy-related functions (economy = Essentials Economy)
01.07 04:56:47 [Server] INFO [HomeSpawnPlus] using VAULT:GroupManager for permissions
01.07 04:56:47 [Server] INFO [HomeSpawnPlus] Loaded 177 locale strings (0 overrides)
01.07 04:56:46 [Server] INFO [HomeSpawnPlus] Enabling HomeSpawnPlus v2.0-b610

server version: 1.8.8 viaversion to 1.10
plugin isnt enabling
if u can please fix this fast i was planning on opening my server tommmorrow the 2th

**Comment by sorifiend** [comment]
You are trying to use a very old version of Homespawn plus that does not work on 1.9.X or 1.10.

If you want a version that works on 1.9 or 1.10 then you need build 637. You can get a copy here:
http://andune.com/jenkins/job/HomeSpawnPlus/637/

**Comment by aycgit** [comment]
@sorifiend bit late but that was the latest build i got from spigot so that needs updating
