### ISSUE TITLE
[1.10.2] NPE during PlayerRespawnEvent.

### ISSUE THREAD

**Issue by SimSonic** [andune/HomeSpawnPlus#107]
Hi!

![image](https://cloud.githubusercontent.com/assets/2697754/17323077/add9988e-58ca-11e6-84d4-50964edff724.png)

Server software: **CraftBukkit version git-Spigot-078e2f8-21e3b05 (MC: 1.10.2) (Implementing API version 1.10.2-R0.1-SNAPSHOT)**

events.yml:

>  onDeath:
> - modeRequiresBed
> - homeMultiWorld
> - modeDefault
> - spawnWorldRandom
> - default

It is latest .jar from your Jenkins.

**Comment by afroman84** [comment]
same error :(

**Comment by andune** [comment]
These reports, as best I can tell, are based on the latest codebase, so if this indeed a bug it is probably still present. I'm trying to clean up old issues, but if you are still having this issue please feel free to re-open and I'll see if I can reproduce so I can hunt it down if it's still an active bug.
