### ISSUE TITLE
Sqlite error on world teleport

### ISSUE THREAD

**Issue by SXRWahrheit** [andune/HomeSpawnPlus#23]
http://pastebin.com/raw.php?i=p58DVkKh

Same as reported before 2.0 update. I use RandomLocation to randomize where players drop in to the nether when they go. It seems like Nether Portals don't trigger it, but any warping or teleporting (including mv portals) does.

**Comment by andune** [comment]
Closing issue as assumed fixed since code was modified to resolve the reported error and no new updates have been posted to indicate this is still a problem. Feel free to re-open case if this is still an isssue.
