### ISSUE TITLE
worldGuardRegion is null

### ISSUE THREAD

**Issue by SimSonic** [andune/HomeSpawnPlus#26]
Hi! I've tried to build HSP by myself (it's a little bit complicated task) because I need WG 6 compatibility and there is no public build with appropriate commit (ec520b1f1b19a961476d8586371f15795ff8876b or other, I don't know if it is working already). I'm building latest commit (6388ff469af37291b6a007f4727f92d506cf584d).
HSP loading and making NPE at WorldEditRegion.java:124 (worldGuardRegion == null).
Can you make stable build with WG 6 support please?

**Comment by SimSonic** [comment]
Sorry, I'm a blind.
Found Jenkins link on DBO and there is latest build. It seems to be working good so I think mentioned problem was caused by my wrong build environment.
Could you add Jenkins link into readme file? :)

**Comment by andune** [comment]
Glad you figured it out. I've added some notes regarding building the project to the README for those who would like to build it themselves.
