### ISSUE TITLE
continuously spams this when debug activated

### ISSUE THREAD

**Issue by Okane84** [andune/HomeSpawnPlus#29]
24.01 16:04:00 [Server] INFO [16:04:00 INFO]: [HomeSpawnPlus] Strategy evaluation started, type=onteleportobserve player={BukkitPlayer:aky004}
24.01 16:04:00 [Server] INFO [16:04:00 INFO]: [HomeSpawnPlus] Strategy evaluation started, type=onteleportobserve player={BukkitPlayer:aky004}
24.01 16:04:00 [Server] INFO [16:04:00 INFO]: [HomeSpawnPlus] Strategy evaluation started, type=onteleportobserve player={BukkitPlayer:aky004}
24.01 16:04:00 [Server] INFO [16:04:00 INFO]: [HomeSpawnPlus] Strategy evaluation started, type=onteleportobserve player={BukkitPlayer:aky004}
24.01 16:04:00 [Server] INFO [16:04:00 INFO]: [HomeSpawnPlus] Strategy evaluation started, type=onteleportobserve player={BukkitPlayer:aky004}
24.01 16:04:00 [Server] INFO [16:04:00 INFO]: [HomeSpawnPlus] Strategy evaluation started, type=onteleportobserve player={BukkitPlayer:aky004}
24.01 16:04:00 [Server] INFO [16:04:00 INFO]: [HomeSpawnPlus] Strategy evaluation started, type=onteleportobserve player={BukkitPlayer:aky004}
24.01 16:04:00 [Server] INFO [16:04:00 INFO]: [HomeSpawnPlus] Strategy evaluation started, type=onteleportobserve player={BukkitPlayer:aky004}
24.01 16:04:00 [Server] INFO [16:04:00 INFO]: [HomeSpawnPlus] Strategy evaluation started, type=onteleportobserve player={BukkitPlayer:aky004}
24.01 16:04:00 [Server] INFO [16:04:00 INFO]: [HomeSpawnPlus] Strategy evaluation started, type=onteleportobserve player={BukkitPlayer:aky004}
24.01 16:04:00 [Server] INFO [16:04:00 INFO]: [HomeSpawnPlus] Strategy evaluation started, type=onteleportobserve player={BukkitPlayer:Vinci_89}
24.01 16:04:00 [Server] INFO [16:04:00 INFO]: [HomeSpawnPlus] Strategy evaluation started, type=onteleportobserve player={BukkitPlayer:Vinci_89}
24.01 16:04:00 [Server] INFO [16:04:00 INFO]: [HomeSpawnPlus] Strategy evaluation started, type=onteleportobserve player={BukkitPlayer:Vinci_89}
24.01 16:04:00 [Server] INFO [16:04:00 INFO]: [HomeSpawnPlus] Strategy evaluation started, type=onteleportobserve player={BukkitPlayer:fede0704}
24.01 16:04:00 [Server] INFO [16:04:00 INFO]: [HomeSpawnPlus] Strategy evaluation started, type=onteleportobserve player={BukkitPlayer:fede0704}
24.01 16:03:59 [Server] INFO [16:03:59 INFO]: [HomeSpawnPlus] Strategy evaluation started, type=onteleportobserve player={BukkitPlayer:Vinci_89}
24.01 16:03:59 [Server] INFO [16:03:59 INFO]: [HomeSpawnPlus] Strategy evaluation started, type=onteleportobserve player={BukkitPlayer:fede0704}

24.01 16:04:00 [Server] INFO [16:04:00 INFO]: [HomeSpawnPlus] Strategy evaluation started, type=onteleportobserve player={BukkitPlayer:aky004}
24.01 16:04:00 [Server] INFO [16:04:00 INFO]: [HomeSpawnPlus] Strategy evaluation started, type=onteleportobserve player={BukkitPlayer:aky004}
24.01 16:04:00 [Server] INFO [16:04:00 INFO]: [HomeSpawnPlus] Strategy evaluation started, type=onteleportobserve player={BukkitPlayer:aky004}
24.01 16:04:00 [Server] INFO [16:04:00 INFO]: [HomeSpawnPlus] Strategy evaluation started, type=onteleportobserve player={BukkitPlayer:aky004}
24.01 16:04:00 [Server] INFO [16:04:00 INFO]: [HomeSpawnPlus] Strategy evaluation started, type=onteleportobserve player={BukkitPlayer:aky004}
24.01 16:04:00 [Server] INFO [16:04:00 INFO]: [HomeSpawnPlus] Strategy evaluation started, type=onteleportobserve player={BukkitPlayer:aky004}
24.01 16:04:00 [Server] INFO [16:04:00 INFO]: [HomeSpawnPlus] Strategy evaluation started, type=onteleportobserve player={BukkitPlayer:aky004}
24.01 16:04:00 [Server] INFO [16:04:00 INFO]: [HomeSpawnPlus] Strategy evaluation started, type=onteleportobserve player={BukkitPlayer:aky004}
24.01 16:04:00 [Server] INFO [16:04:00 INFO]: [HomeSpawnPlus] Strategy evaluation started, type=onteleportobserve player={BukkitPlayer:aky004}
24.01 16:04:00 [Server] INFO [16:04:00 INFO]: [HomeSpawnPlus] Strategy evaluation started, type=onteleportobserve player={BukkitPlayer:aky004}
24.01 16:04:00 [Server] INFO [16:04:00 INFO]: [HomeSpawnPlus] Strategy evaluation started, type=onteleportobserve player={BukkitPlayer:Vinci_89}
24.01 16:04:00 [Server] INFO [16:04:00 INFO]: [HomeSpawnPlus] Strategy evaluation started, type=onteleportobserve player={BukkitPlayer:Vinci_89}
24.01 16:04:00 [Server] INFO [16:04:00 INFO]: [HomeSpawnPlus] Strategy evaluation started, type=onteleportobserve player={BukkitPlayer:Vinci_89}
24.01 16:04:00 [Server] INFO [16:04:00 INFO]: [HomeSpawnPlus] Strategy evaluation started, type=onteleportobserve player={BukkitPlayer:fede0704}
24.01 16:04:00 [Server] INFO [16:04:00 INFO]: [HomeSpawnPlus] Strategy evaluation started, type=onteleportobserve player={BukkitPlayer:fede0704}
24.01 16:03:59 [Server] INFO [16:03:59 INFO]: [HomeSpawnPlus] Strategy evaluation started, type=onteleportobserve player={BukkitPlayer:Vinci_89}
24.01 16:03:59 [Server] INFO [16:03:59 INFO]: [HomeSpawnPlus] Strategy evaluation started, type=onteleportobserve player={BukkitPlayer:fede0704}

i don't know why or when, i use the random spawn strategy explained in a previous ticket

**Comment by andune** [comment]
What version of HSP? I've seen this behavior myself, I believe it's a bug in 1.8 (Spigot) because all of these teleports are real events from the server and in my testing, they are the player being teleported to the same exact location dozens of times in the same second. I added code to detect and drop these spurious teleport events as of build 596:

http://andune.com/jenkins/job/HomeSpawnPlus/596/changes

If you're running 596 or higher I'd be interested if you are still getting these.

**Comment by Okane84** [comment]
Hello, i was using the build 589, now with the latest (599) no more
spamming of teleports.
I'll keep you up if i notice something wrong.
i'd have a request: something to output what spawn has a player (i mean the
spawnLocalPlayerSpawn), and / or the bed where is.
something like /returnplayerspawn <nickname>
@return:
<nickname> has this spawn set: id(4) name(Spawn1) x, y, z
<nickname> has this home set: id(2) name(bed1) x y z
or <nickname> has not set any home

thank you

2015-01-24 17:32 GMT+01:00 andune <notifications@github.com>:
