### ISSUE TITLE
Cooldowns per permission or world doesn't seem to work

### ISSUE THREAD

**Issue by Bakurawr** [andune/HomeSpawnPlus#33]
Whenever you try to setup cooldowns based on per world or permission it seems to make the plugin automatically get an exception at startup which disables the plugin, something that worked fine pre 2.0.

Here's a link that include the two variants of the errors I have, the latter is made when I remove the world part all together or just move permission below it so it seems it's tied to the same issue.
https://www.dropbox.com/s/uwj4b9kpw3jxrjw/errors.txt?dl=0

And here's the current configs and also version used (#606, also tried with others in 2.0, same issue) however without the database included.
https://www.dropbox.com/s/859ht1azbxqzzri/HomeSpawnPlus.zip?dl=0

**Comment by andune** [comment]
Thanks for the report. Should be fixed in build 607.
Might still be issues with cooldowns themselves since I haven't tested them, but at least it will startup and has the configs loaded properly in memory now. Give it a test and please open new issues for any other bugs you find.
