### ISSUE TITLE
Warmups/Cooldowns not working

### ISSUE THREAD

**Issue by Favorlock** [andune/HomeSpawnPlus#47]
Compiled using https://github.com/andune/HomeSpawnPlus/commit/fe949742d35e029d1aff8bcd02d46348349c9a23

`warmup:
  enabled: true
  onMoveCancel: true
  onDamageCancel: true
  home: 5
  spawn: 5
  groupspawn: 5`

**Comment by andune** [comment]
It's working fine for me in the latest version, this code hasn't changed any in a while so this is working as far back as first 2.0 alpha release as far as I know.

If you're having an issue can you provide more detail? Do you get a stack trace on error? Are you an admin/op with all permissions? If so, you need to exclude the warmup exemption permissions. Doing this on PEX as an example is something like:

```
pex group Admin add -hsp.WarmupExempt.*
```
