### ISSUE TITLE
[req] New event: falling down the world.

### ISSUE THREAD

**Issue by SimSonic** [andune/HomeSpawnPlus#52]
It's quite simple.
When player falls down event is triggered and strategy chain is executed.
default action is no action, he will die.

**Comment by andune** [comment]
This is now implemented as "onFallThroughWorld", as in:

```
events:
  onFallThroughWorld:
    - homeMultiWorld
```

If defined and a location is returned from the strategy chain, the player will be teleported safely to the destination rather than killed.

**Comment by SimSonic** [comment]
Thanks a lot!
