### ISSUE TITLE
Could not pass PlayerJoinEvent

### ISSUE THREAD

**Issue by Chaka15205** [andune/HomeSpawnPlus#61]
When the PlayerJoinEvent is called HSP is printing the following stacktrace.

http://pastebin.com/SxzdeWer

**Comment by andune** [comment]
The only way I know for this to happen is through multiple updates in some early 2.0 betas that had some schema issues - though it's certainly possible something else is going on.

Probably the most straightforward fix is to use "/hsp backup" to backup your existing database, then shutdown server, remove the current DB and restart server. This will initialize an empty database which you can then "/hsp restore" all of your data to.

**Comment by Chaka15205** [comment]
It worked, Thanks.
