### ISSUE TITLE
unable to convert essentials

### ISSUE THREAD

**Issue by frizzbee30** [andune/HomeSpawnPlus#66]
Hi, this works great in test, however in live it is unable to convert the database. It initially threw an ebeans error, but I added a blank ebeans.properties file to get around this issue. I also tried YAML storage as well as ebeans, but both give the same error on trying conversion.

  
  # This is one option that cannot be reloaded live with "/hsp rc",
  # you must restart Bukkit if you change this option.
  storage: EBEANS

bukkit.yml

database:
  username: bukkit
  isolation: SERIALIZABLE
  driver: org.sqlite.JDBC
  password: xxxxx
  url: jdbc:sqlite:{DIR}{NAME}.db

Spigot version  1.8.5 latest commit

Error log on using EBEANS

http://pastebin.com/3TqHBFeX

Homespawnplus loads normally with no errors in the log file

**Comment by frizzbee30** [comment]
latest jenkins build of HSP

**Comment by andune** [comment]
The ebeans error is benign, but I'm glad blanking out the ebeans.properties makes it go away, I didn't know that.

Thank you for the stack trace. It looks like a problem with the import format for Essentials. Pretty sure I updated it recently, but Essentials is revving all the time so it's quite possible the latest version has changed formats and I need to adjust the converter. What version of Essentials are you running?

**Comment by frizzbee30** [comment]
Hi, I wondered if was was the version update, although oddly it worked in test  (which is a clone of live). Here's the essentials link https://hub.spigotmc.org/jenkins/job/Spigot-Essentials/  it's version 12 we are using. Thanks

**Comment by andune** [comment]
I did a quick review of the Essentials code and I don't see that their format has changed in quite some time, at least in the latest stable releases. It's entirely possible this is a corrupt file that is blowing up the YAML parser. If you want to troubleshoot yourself, create an empty file named 'devDebug' (in UNIX: 'touch') in your plugins/HomeSpawnPlus folder. After a restart, HSP will see that and start emitting extremely verbose debug messages and when you run your import, you'll get a lot more detail about which file it's choking on. If you don't want to do that in production, I'd recommend backing up your Essentials directory and copying it to your test server to see if you can reproduce the import issue there.

If that doesn't help, feel free to zip up your Essentials directory and send me a link and I'll download and do the same thing, I should be able to figure out a lot more about what is going on with the actual Essentials files in hand to test with.

**Comment by frizzbee30** [comment]
Hi, thanks, I'll send you a pm in bukkit dev with the dropbox link. I think you'll probably get more out of the crunching than I will (potentially I would be getting back to you with the results/query  :)  ) I'm just working on the zipping now. Thanks for looking into this, we are really keen to get the plugin live  :D

**Comment by frizzbee30** [comment]
ok, I think I figured the issue (yet to test), our host has at best a 'flakey' FTP connection, on going to pull the essentials data there are a lot of tmp files in there. I'm guessing it tries to import all data from the essentials data folder and spits out it's dummy at the gs_tmp transfer files from previous failed uploads. I'm going to clean up a bit and try again.

**Comment by frizzbee30** [comment]
cleaning the gs_tmp files fixed it!  Thanks for all the input and a great plugin!
