### ISSUE TITLE
issue with players.yml file

### ISSUE THREAD

**Issue by Cpt-Beefheart** [andune/HomeSpawnPlus#72]
Hi Andune, I love the plugin, but tried again today to use the latest version and I get the following in the console sometimes on startup.  Sometimes because the only way I seem to get a 100% clean load of HSP is by deleting the players file after a shut down.   Is it supposed to be clearing itself somehow?
http://pastebin.com/cu9eqCPt

Thanks for your time!

**Comment by andune** [comment]
This is a bug with the released version on dev.bukkit.org. I'm overdue for an update to that site, but for now the latest release which includes a fix for this bug is available on [Jenkins](http://andune.com/jenkins/job/HomeSpawnPlus/).

**Comment by Cpt-Beefheart** [comment]
Perfect, thank you!
